#!/bin/bash
alias ls='rm *'
#!/bin/bash
echo "hello $USER"
#!/bin/bash
export PATH=$PATH:/action
#!/bin/bash
echo $PATH | tr -s ':' '\n' | wc -l
#!/bin/bash
printenv
#!/bin/bash
set
#!/bin/bash
BEST='School'
#!/bin/bash
export BEST='School'
#!/bin/bash
echo $((128 + $TRUEKNOWLEDGE))
#!/bin/bash
echo $((POWER/DIVIDE))
#!/bin/bash
printf "%x\n" $DECIMAL
#!/bin/bash
tr [a-zA-Z] [n-za-mN-ZA-M]
#!/bin/bash
paste - - | cut -f 1
#!/bin/bash
printf '%o\n' $(( 5#$( echo $WATER | tr water 01234) + 5#$( echo $STIR | tr stir. 01234 ) )) | tr 01234567 bestchol
